---
# yamllint disable rule:line-length
image: registry.opensuse.org/home/okurz/container/ca/containers/tumbleweed:salt-minion-git-core-ssh

stages:
  - test-static
  - test
  - deploy
  - post-deploy

variables:
  GIT_DEPTH: "3"
  # make sure to apply workaround for
  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4119
  # within script sections as salt calls can take long
  salt_call: podman exec -e LANG=en_US.UTF-8 test-target salt-call --local state.apply

.test_setup: &test_setup
  stage: test
  # our test steps can fail especially on repository refresh errors so let's
  # retry
  retry: 2
  except:
    - master@openqa/salt-pillars-openqa
  before_script:
    - podman run -d --name test-target --systemd=always -v $(pwd -P):/srv/salt:ro -v $(pwd -P)/t/pillar:/srv/pillar:ro registry.opensuse.org/home/okurz/container/ca/containers/tumbleweed:salt-minion-git-core-ssh /usr/lib/systemd/systemd
    - until podman exec test-target systemctl is-system-running | grep -E "running|degraded"; do sleep 0.05; done
    - podman exec test-target sh -c "mkdir -p /etc/salt && echo -e 'disable_grains:\n  - esxi\n\ndisable_modules:\n  - vsphere' > /etc/salt/minion"
    - podman exec test-target rm -f /usr/lib/zypp/plugins/commit/zyppnotify
  after_script:
    - podman rm -f test-target || true


test-general-mock:
  <<: *test_setup
  stage: test-static
  script: $salt_call mock=True

test-webui-mock:
  <<: *test_setup
  stage: test-static
  script:
    - podman exec test-target sh -c "echo 'roles: webui' >> /etc/salt/grains"
    - $salt_call mock=True

test-worker-mock:
  <<: *test_setup
  stage: test-static
  script:
    - podman exec test-target sh -c "echo 'roles: worker' >> /etc/salt/grains"
    - $salt_call mock=True

test-monitor-mock:
  <<: *test_setup
  stage: test-static
  script:
    - podman exec test-target sh -c "echo 'roles: monitor' >> /etc/salt/grains"
    - $salt_call mock=True

test-storage-mock:
  <<: *test_setup
  stage: test-static
  script:
    - podman exec test-target sh -c "echo 'roles: storage' >> /etc/salt/grains"
    - $salt_call mock=True

test-jenkins-mock:
  <<: *test_setup
  stage: test-static
  script:
    - podman exec test-target sh -c "echo 'roles: jenkins' >> /etc/salt/grains"
    - $salt_call mock=True

test-libvirt-mock:
  <<: *test_setup
  stage: test-static
  script:
    - podman exec test-target sh -c "echo 'roles: libvirt' >> /etc/salt/grains"
    - $salt_call mock=True

test-general-test:
  <<: *test_setup
  script: $salt_call test=True

test-general:
  <<: *test_setup
  script:
    - $salt_call

test-unit:
  script:
    - zypper --non-interactive in python3-pytest
    - pytest

test-webui:
  <<: *test_setup
  script:
    - podman exec test-target sh -c "echo 'roles: webui' >> /etc/salt/grains"
    - podman exec test-target sh -c "echo 'webserver: apache2' >> /etc/salt/grains"
    - (
    - trap "kill %1" EXIT; while true; do sleep 1 && echo -n .; done &
    - $salt_call
    - )
    # files must exist after correct salt application and can be inspected
    # manually
    - podman exec test-target cat /etc/openqa/openqa.ini.d/*

test-worker:
  <<: *test_setup
  script:
    - podman exec test-target sh -c "echo 'roles: worker' >> /etc/salt/grains"
    # just pick any example worker for testing purposes
    - sed -i -e "s/openqaworker3/$HOSTNAME/" /srv/pillar/openqa/workerconf.sls
    - (
    - trap "kill %1" EXIT; while true; do sleep 1 && echo -n .; done &
    - $salt_call
    - )
    - podman exec test-target cat /etc/openqa/workers.ini

test-monitor:
  <<: *test_setup
  script:
    - podman exec test-target sh -c "echo 'roles: monitor' >> /etc/salt/grains"
    - podman exec test-target sh -c "echo 'webserver: nginx' >> /etc/salt/grains"
    - (
    - trap "kill %1" EXIT; while true; do sleep 1 && echo -n .; done &
    - $salt_call
    - )
    # some checks on the changed or generated files
    - podman exec test-target ls /etc/nginx/vhosts.d/
    - podman exec test-target sh -c "grep -q 'monitor.qa.suse.de' /etc/nginx/vhosts.d/02-grafana.conf && echo 'ok -- expected nginx config file for grafana exists'"
    - podman exec test-target sh -c "(telegraf --test --input-filter system ||:) | grep -q 'system,host='"

test-storage:
  <<: *test_setup
  script:
    - podman exec test-target sh -c "echo 'roles: storage' >> /etc/salt/grains"
    - (
    - trap "kill %1" EXIT; while true; do sleep 1 && echo -n .; done &
    - $salt_call
    - )

test-jenkins:
  <<: *test_setup
  script:
    - podman exec test-target sh -c "echo 'roles: jenkins' >> /etc/salt/grains"
    - $salt_call

test-libvirt:
  <<: *test_setup
  script:
    - podman exec test-target sh -c "echo 'roles: libvirt' >> /etc/salt/grains"
    - $salt_call


include:
  - test-static.yml
  - deploy.yml
