{
 "title": "Agile",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "30m",
 "panels": [
  {
   "title": "QE Tools backlog - stacked",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "In Feedback",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "team",
       "operator": "=",
       "value": "\"QE Tools\""
      },
      {
       "condition": "AND",
       "key": "title",
       "operator": "=",
       "value": "\"Combined Backlog (dev+infra)\""
      },
      {
       "condition": "AND",
       "key": "status",
       "operator": "=",
       "value": "\"Feedback\""
      }
     ]
    },
    {
     "alias": "In Progress",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "team",
       "operator": "=",
       "value": "\"QE Tools\""
      },
      {
       "condition": "AND",
       "key": "title",
       "operator": "=",
       "value": "\"Combined Backlog (dev+infra)\""
      },
      {
       "condition": "AND",
       "key": "status",
       "operator": "=",
       "value": "\"In Progress\""
      }
     ]
    },
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "team",
       "operator": "=",
       "value": "\"QE Tools\""
      },
      {
       "condition": "AND",
       "key": "title",
       "operator": "=",
       "value": "\"Combined Backlog (dev+infra)\""
      },
      {
       "condition": "AND",
       "key": "status",
       "operator": "=",
       "value": "\"New\""
      }
     ]
    },
    {
     "alias": "Workable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "team",
       "operator": "=",
       "value": "\"QE Tools\""
      },
      {
       "condition": "AND",
       "key": "title",
       "operator": "=",
       "value": "\"Combined Backlog (dev+infra)\""
      },
      {
       "condition": "AND",
       "key": "status",
       "operator": "=",
       "value": "\"Workable\""
      }
     ]
    },
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "team",
       "operator": "=",
       "value": "\"QE Tools\""
      },
      {
       "condition": "AND",
       "key": "title",
       "operator": "=",
       "value": "\"Combined Backlog (dev+infra)\""
      },
      {
       "condition": "AND",
       "key": "status",
       "operator": "=",
       "value": "\"Blocked\""
      }
     ]
    }
   ]
  },
  {
   "title": "QE Tools Team Lead & Cycle Time",
   "type": "timeseries",
   "description": "- Lead time measures the total time from when a task is created until it is completed, this is our overall responsiveness.\n- Cycle time starts when work begins on a task and ends when it is finished, this is our efficiency.\n\nA short lead time means faster response to new task, while a lower cycle time indicates smooth task execution. Longer times may signal bottlenecks or complex work.\n\nMore details: [team wiki](https://progress.opensuse.org/projects/qa/wiki/Tools#How-we-work-on-our-backlog)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "mean cycleTime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "leadTime",
     "query": "SELECT ((sum(\"cycleTimeSum\") / sum(\"count\")))/24 FROM \"leadTime\" WHERE (\"team\" = '\"QE Tools\"' AND \"status\" = '\"Resolved\"') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "mean leadTime",
     "query": "SELECT ((sum(\"leadTimeSum\") / sum(\"count\")))/24 FROM \"leadTime\" WHERE (\"team\" = '\"QE Tools\"' AND \"status\" = '\"Resolved\"') AND $timeFilter GROUP BY time($__interval) fill(none)"
    },
    {
     "alias": "cycleTime 10d avg",
     "query": "SELECT ((sum(\"cycleTimeSum\") / sum(\"count\")))/24 FROM \"leadTime\" WHERE (\"team\" = '\"QE Tools\"' AND \"status\" = '\"Resolved\"') AND $timeFilter GROUP BY time($__interval*10) fill(none)"
    },
    {
     "alias": "cycleTime 30d avg",
     "query": "SELECT ((sum(\"cycleTimeSum\") / sum(\"count\")))/24 FROM \"leadTime\" WHERE (\"team\" = '\"QE Tools\"' AND \"status\" = '\"Resolved\"') AND $timeFilter GROUP BY time($__interval*30) fill(none)"
    }
   ]
  },
  {
   "title": "QE Tools - closed tickets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "Closed Tickets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "leadTime",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "team",
       "operator": "=",
       "value": "\"QE Tools\""
      },
      {
       "condition": "AND",
       "key": "title",
       "operator": "=",
       "value": "\"Closed yesterday\""
      },
      {
       "condition": "AND",
       "key": "status",
       "operator": "=",
       "value": "\"Resolved\""
      }
     ]
    }
   ]
  }
 ]
}