{
 "title": "Failed systemd services",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Failing services in selected time range",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select units,last(failed) from systemd_failed where $timeFilter and (\"failed\">0)  group by host",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Failed systemd services (openqa.suse.de)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "systemd_failed",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "openqa" }
     ]
    }
   ]
  },
  {
   "title": "Failed systemd services (except openqa.suse.de)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sum of failed systemd services",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "systemd_failed",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!=", "value": "openqa" }
     ]
    }
   ]
  },
  {
   "title": "Masked systemd services (except openqa.suse.de)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Sum of masked systemd services",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "systemd_masked",
     "select": [
      [
       { "params": [ "masked" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "!=", "value": "openqa" }
     ]
    }
   ]
  }
 ]
}