{
 "title": "Iam metrics",
 "time": { "from": "2024-04-28T00:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "QE Yam issues",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "In progress",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "status::tag",
       "operator": "=",
       "value": "\"In Progress\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"Issues IN_PROGRESS\""
      }
     ]
    },
    {
     "alias": "Workable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"Workable issues\""
      }
     ]
    },
    {
     "alias": "Created last 24h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"QE Yam new actions per day\""
      }
     ]
    },
    {
     "alias": "New",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"QE Yam all new actions\""
      }
     ]
    }
   ]
  },
  {
   "title": "Resolved per day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "Resolved tickets",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "leadTime",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"Resolved yesterday\""
      }
     ]
    }
   ]
  },
  {
   "title": "Tickets created last 24h",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Tickets created last 24h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"QE Yam new actions per day\""
      }
     ]
    }
   ]
  },
  {
   "title": "Actions with status NEW",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"QE Yam all new actions\""
      }
     ]
    }
   ]
  },
  {
   "title": "Workable ",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Workable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"Workable issues\""
      }
     ]
    }
   ]
  },
  {
   "title": "In progress",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"Issues IN_PROGRESS\""
      }
     ]
    }
   ]
  },
  {
   "title": "Softfailure mitigations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 16, "y": 19 },
   "targets": [
    {
     "alias": "Workable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"Softfailures workable\""
      }
     ]
    },
    {
     "alias": "In Progress",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "slo",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"Softfailures in progress\""
      }
     ]
    },
    {
     "alias": "Resolved",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "leadTime",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "team::tag",
       "operator": "=",
       "value": "\"QE Yam\""
      },
      {
       "condition": "AND",
       "key": "title::tag",
       "operator": "=",
       "value": "\"Softfailures resovled\""
      }
     ]
    }
   ]
  },
  {
   "title": "YAML File in \"schedule/yam/\": trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "qe_yam_schedule_yaml",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "YAML File in \"schedule/yam/\" : current",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 19, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "qe_yam_schedule_yaml",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}