{
 "title": "Monitoring",
 "description": "Panels/alerts for the monitoring itself",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Packet loss between worker hosts and other hosts",
   "type": "table",
   "description": "Shows packet loss within the the QA network infrastructure.\n\nThe first hostname is a salt managed host. The second hostname is a host listed under `required_external_networks` in `workerconf.sls` in the pillars repository that is pinged from the source host. See https://gitlab.suse.de/suse/wiki/-/blob/main/qe_infrastructure.md for details about hosts.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host - $tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT mean(\"percent_packet_loss\") FROM \"ping\" WHERE (\"network\"::tag = 'external') AND $timeFilter GROUP BY time($__interval), \"url\", \"host\" fill(null)",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "network::tag", "operator": "=", "value": "external" }
     ]
    }
   ]
  },
  {
   "title": "HTTP response time between worker hosts and other hosts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_server - $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "server::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Panel for InfluxDB alert",
   "type": "timeseries",
   "description": "This panel contains no data. Its only purpose is the InfluxDB alert.\n\nThis alert is only supposed to catch \"execution errors\" like `tsdb.HandleRequest() error Get \"http://localhost:8086/query?…: dial tcp [::1]:8086: connect: connection refused`. Hence there's just a query which is never supposed to return any data which is treated as \"ok\" and only execution errors trigger the alert.",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "measurement": "non-existant",
     "select": [
      [
       { "params": [ "failed" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}