{
 "title": "OpenQA Jobs test",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Queue: State (SUSE)",
   "type": "timeseries",
   "description": "All running, scheduled and blocked openQA jobs. Alert thresholds are defined per individual as well as cumulative values hence the lower displayed threshold bar can be exceeded by the sum of values.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Running",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "https://openqa.suse.de" }
     ]
    },
    {
     "alias": "Scheduled",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs",
     "select": [
      [
       { "params": [ "scheduled" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "https://openqa.suse.de" }
     ]
    },
    {
     "alias": "Blocked",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs",
     "query": "SELECT mean(\"blocked\") FROM \"openqa_jobs\" WHERE (\"url\" = 'https://openqa.suse.de') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "blocked" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "https://openqa.suse.de" }
     ]
    }
   ]
  },
  {
   "title": "Queue: Groups (SUSE)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_group",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs_by_group",
     "query": "SELECT mean(\"running\") + mean(\"scheduled\") + mean(\"blocked\") FROM \"openqa_jobs_by_group\" WHERE (\"url\" = 'https://openqa.suse.de') AND $timeFilter GROUP BY time($__interval), \"group\" fill(0)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "https://openqa.opensuse.org" }
     ]
    }
   ]
  },
  {
   "title": "Queue: Architecture (SUSE)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_arch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "arch" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs_by_arch",
     "query": "SELECT mean(\"running\") + mean(\"scheduled\") + mean(\"blocked\") FROM \"openqa_jobs_by_arch\" WHERE (\"url\" = 'https://openqa.suse.de') AND (\"arch\"::tag =~ /^[A-Za-z0-9_-]+$/) AND $timeFilter GROUP BY time($__interval), \"arch\" fill(0)",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Running by Worker (SUSE)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_worker",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "worker" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "openqa_jobs_by_worker",
     "select": [
      [
       { "params": [ "running" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=", "value": "https://openqa.suse.de" }
     ]
    }
   ]
  },
  {
   "title": "Incomplete jobs of last 24h",
   "type": "timeseries",
   "description": "Automatic labelling of incompletes, fails on unknown, new issues: https://gitlab.suse.de/openqa/auto-review/pipelines",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Incompletes of last 24h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "incompletes_last_24h" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "New incompletes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "New incompletes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "incompletes_last_24h" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Incomplete jobs (not restarted) of last 24h",
   "type": "timeseries",
   "description": "Automatic labelling of incompletes, fails on unknown, new issues: https://gitlab.suse.de/openqa/auto-review/pipelines",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Incompletes (not restarted) of last 24h",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       {
        "params": [
         "incompletes_not_restarted_last_24h"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "openQA job fail ratio",
   "type": "timeseries",
   "description": "Ratio of failed vs. all jobs over time.\n\nhttps://progress.opensuse.org/issues/96191",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "ratio of failed openQA jobs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "ratio_failed_p" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ratio of not restarted multi-machine tests by result",
   "type": "piechart",
   "description": "https://progress.opensuse.org/issues/96191",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "ratio_mm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ratio of not restarted multi-machine tests by result",
   "type": "timeseries",
   "description": "https://progress.opensuse.org/issues/96191",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "ratio_mm" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ratio of tests by result (all-time)",
   "type": "timeseries",
   "description": "https://progress.opensuse.org/issues/96191",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "ratio_all_long_term" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ratio of not restarted multi-machine tests by result (all-time)",
   "type": "timeseries",
   "description": "https://progress.opensuse.org/issues/96191",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_result",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "result" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "ratio_mm_long_term" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ratio of failed tests by worker host (all-time)",
   "type": "timeseries",
   "description": "https://progress.opensuse.org/issues/99135",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "ratio_failed_by_host" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Approximate result size by job group",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "targets": [
    {
     "alias": "$tag_group_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "group_name" ], "type": "tag" }
     ],
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "result_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ "/ 1024 / 1024 / 1024" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}