{
 "title": "Hana-Perf gitlab metrics",
 "time": { "from": "now-2y", "to": "now" },
 "panels": [
  { "title": "Commits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commits on Project M",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "commits::field" ], "type": "tag" }
     ],
     "measurement": "Project_C",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "commits::field" ], "type": "tag" }
     ],
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "commits::field" ], "type": "tag" }
     ],
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "commits::field" ], "type": "tag" }
     ],
     "measurement": "Project_P",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "commits::field" ], "type": "tag" }
     ],
     "measurement": "HANAPERF_CI",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commits on project P",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "measurement": "Project_P",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commits on Project K",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "[Heatmap] Commits on all projects",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "measurement": "Project_C",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    },
    {
     "measurement": "Project_P",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commits on Project C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "measurement": "Project_C",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Commits on HANAPERF_CI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "measurement": "HANAPERF_CI",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Issues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Project_M total issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Opened",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "opened_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Closed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "closed_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Project_M issue age (days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "issue_age" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Project_M",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 34 },
   "targets": [
    {
     "alias": "opened issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "opened_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "closed issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "closed_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "commits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_M",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HANAPERF_CI total issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Opened",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HANAPERF_CI",
     "select": [
      [
       { "params": [ "opened_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Closed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HANAPERF_CI",
     "select": [
      [
       { "params": [ "closed_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HANAPERF_CI issue age (days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HANAPERF_CI",
     "select": [
      [
       { "params": [ "issue_age" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HANAPERF_CI",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 40 },
   "targets": [
    {
     "alias": "opened issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HANAPERF_CI",
     "select": [
      [
       { "params": [ "opened_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "closed issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HANAPERF_CI",
     "select": [
      [
       { "params": [ "closed_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "commits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HANAPERF_CI",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PROJECT_K total issues",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Opened",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "opened_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Closed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "closed_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PROJECT_K issue age (days)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 4, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "issue_age" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PROJECT_K",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 46 },
   "targets": [
    {
     "alias": "opened issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "opened_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "closed issues",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "closed_issues" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "commits",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Project_K",
     "select": [
      [
       { "params": [ "commits" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}