{
 "title": "sleperf_metrics",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "SLE-Performance milestone testing metrics",
   "type": "barchart",
   "description": "The x-axis is milestone, the y-axis is case running number (Case number X Machine number)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT \"milestone\",\"total-run-times\",\"pass-times\",\"fail-times\" FROM \"autogen\".sle_perf_status WHERE \"role\" = 'performance' and time > now() - 12h"
    }
   ]
  },
  {
   "title": "Virtualization-Performance milestone testing metrics",
   "type": "barchart",
   "description": "The x-axis is milestone, the y-axis is case running number (Case number X Machine number)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT \"milestone\",\"total-run-times\",\"pass-times\",\"fail-times\" FROM \"autogen\".sle_perf_status WHERE \"role\"='Virt-Performance'  and time > now() - 12h"
    }
   ]
  },
  {
   "title": "SLEPerf Gitlab Total Commits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"commits\") FROM \"autogen\".SLEPerf WHERE $timeFilter "
    }
   ]
  },
  {
   "title": "SLEPerf Gitlab Commits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 18 },
   "targets": [
    {
     "query": "SELECT \"commits\" FROM \"autogen\".SLEPerf WHERE $timeFilter"
    }
   ]
  }
 ]
}