apiVersion: 1
groups:
  - orgId: 1
    name: systemd_failed
    folder: Salt
    interval: 1m
    rules:
      - uid: beefj548t0a2oc
        title: Systemd services
        condition: Threshold
        data:
          - refId: failed systemd units per machine
            relativeTimeRange:
              from: 300
              to: 0
            datasourceUid: "000000001"
            model:
              groupBy:
                - params:
                    - machine::tag
                  type: tag
                - params:
                    - unit_1::tag
                  type: tag
                - params:
                    - unit_2::tag
                  type: tag
              interval: 1m
              intervalMs: 1000
              maxDataPoints: 43200
              measurement: systemd_failed
              orderByTime: ASC
              policy: default
              query: SELECT "failed" FROM "systemd_failed" WHERE $timeFilter GROUP BY "machine"::tag, "unit_1"::tag, "unit_2"::tag, "unit_3"::tag, "unit_4"::tag, "unit_5"::tag
              rawQuery: true
              refId: failed systemd units per machine
              resultFormat: time_series
              select:
                - - params:
                      - failed
                    type: field
              tags: []
          - refId: Number of failed systemd units
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: failed systemd units per machine
              intervalMs: 1000
              maxDataPoints: 43200
              reducer: last
              refId: Number of failed systemd units
              type: reduce
          - refId: Threshold
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params: []
                  reducer:
                    params: []
                    type: avg
                  type: query
              datasource:
                name: Expression
                type: __expr__
                uid: __expr__
              expression: Number of failed systemd units
              intervalMs: 1000
              maxDataPoints: 43200
              refId: Threshold
              type: threshold
        dashboardUid: KToPYLEWz
        panelId: 6
        noDataState: OK
        execErrState: KeepLast
        for: 5m
        annotations:
          __alertId__: "199"
          __dashboardUid__: KToPYLEWz
          __panelId__: "6"
          description: This alert collects `systemctl --failed` and notifies about any machine having more than zero failed units.
          runbook_url: https://progress.opensuse.org/projects/qa/wiki/Tools#Alert-handling
        labels:
          __contacts__: '"osd-admins"'
          rule_uid: Uk02cifVkz
        isPaused: false
