---
apiVersion: 1
groups:
  - orgId: 1
    name: monitor.qa.suse.de - No Data alert
    folder: Salt
    interval: 1m
    rules:
      - uid: belus0ujm61oge
        title: QE Tools backlog - No Data Alert
        condition: A
        data:
          - refId: no-data-query
            relativeTimeRange:
              from: 43200
              to: 0
            datasourceUid: '000000001'
            model:
              alias: In Feedback
              groupBy:
                - params:
                    - $__interval
                  type: time
                - params:
                    - 'null'
                  type: fill
              intervalMs: 14400000
              measurement: slo
              orderByTime: ASC
              policy: default
              refId: no-data-query
              resultFormat: time_series
              select:
                - - params:
                      - count
                    type: field
                  - params: []
                    type: mean
              tags:
                - key: team
                  operator: =
                  value: '"QE Tools"'
                - condition: AND
                  key: title
                  operator: =
                  value: '"Combined Backlog (dev+infra)"'
                - condition: AND
                  key: status
                  operator: =
                  value: '"Feedback"'
          - refId: A
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - -9999
                      - 0
                    type: lt
                  operator:
                    type: and
                  query:
                    params:
                      - no-data-query
                  reducer:
                    type: last
              intervalMs: 1000
              maxDataPoints: 43200
              refId: A
              type: classic_conditions
        dashboardUid: ck8uu5f4z
        panelId: 2
        noDataState: Alerting
        execErrState: Error
        for: 5m
        annotations:
          __dashboardUid__: ck8uu5f4z
          __panelId__: '2'
          message: >-
            There is no data received by the qa-tools stacked backlog panel.
            Check that data collection is working properly and the InfluxDB
            connections are functioning.
          runbook_url: 'https://progress.opensuse.org/issues/181703'
        labels:
          __contacts__: '"osd-admins"'
          rule_uid: belus0ujm61oge
        isPaused: false
