#!/bin/bash -e

if [[ $(df --output=pcent "/var/lib/libvirt/images"| tail -1 | sed 's/^ *//;s/%$//') -gt 70 ]] ; then
    find /var/lib/libvirt/images/*.qcow2 -ignore_readdir_race ! -exec fuser -s "{}" \; -exec rm -f {} \; 2>/dev/null
fi
