#!/bin/bash -e

if [[ $(df | grep "/var/lib/libvirt/images" | awk '{print $5}' | sed "s/\%//") -gt 70 ]] ; then
    find /var/lib/libvirt/images/*.qcow2 -ignore_readdir_race ! -exec fuser -s "{}" \; -delete 1>/dev/null
fi
