#!/bin/bash
# Script to setup worker bridge for openvswitch for os-autoinst
# Based on documentation at https://github.com/os-autoinst/openQA/blob/master/docs/Networking.asciidoc
# Expects openvswitch service to be enabled and running
# This file is generated by salt - don't touch
# Hosted on https://gitlab.suse.de/openqa/salt-states-openqa


ovs-vsctl add-br br1
ip addr add 10.0.2.2/15 dev br1
ip route add 10.0.0.0/15 dev br1
ip link set br1 up
brctl addif br1 {{ pillar['workerconf'][grains['host']]['bridge_port'] }}
