#[auth]
#method = OAuth2

[oauth2]
provider = custom
authorize_url = https://id.suse.com/application/o/authorize/?response_type=code
token_url = https://id.suse.com/application/o/token/
user_url = https://id.suse.com/application/o/userinfo/
token_scope = email profile openid sub communityUidAsopenId
token_label = Bearer
id_from = communityUidAsopenId
nickname_from = sub
unique_name = suseid
key = {{ pillar['server']['oauth2']['client_id'] }}
secret = {{ pillar['server']['oauth2']['client_secret'] }}
